### ISSUE TITLE
self-critical sequence training: _sample() takes at least 3 arguments (2 given)

### ISSUE THREAD

**Issue by arjung128** [ruotianluo/self-critical.pytorch#120]
I got the cross-entropy training to successfully train, now I am trying to get the self-critical sequence training portion of the training to work. The self-critical sequence training portion successfully trains for a little less than an epoch until it gives me the following error:

```
Traceback (most recent call last):
  File "train.py", line 267, in <module>
    train(opt)
  File "train.py", line 215, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/arjun/self-critical.pytorch/eval_utils.py", line 121, in eval_split
    seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
  File "/home/arjun/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/arjun/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/arjun/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/arjun/anaconda2/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
TypeError: _sample() takes at least 3 arguments (2 given)
Terminating BlobFetcher
```

Any ideas why this may be occurring?

Any and all ideas will be much appreciated, thanks!

**Comment by ruotianluo** [comment]
Is the error still there?
