### ISSUE TITLE
TypeError when evaluating 

### ISSUE THREAD

**Issue by sssilence** [ruotianluo/self-critical.pytorch#151]
python eval.py --model log_fc/model.pth --infos_path infos_fc.pkl --image_folder blah --num_images 10
DataLoaderRaw loading images from folder:  blah0
listing all images in directory blah
DataLoaderRaw found  20  images10
Traceback (most recent call last):
  File "eval.py", line 76, in <module>
    vars(opt))
  File "/home/ps/ws/code/self-critical.pytorch-master/eval_utils.py", line 124, in eval_split
    seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
  File "/home/ps/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ps/ws/code/self-critical.pytorch-master/models/CaptionModel.py", line 32, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 156, in _sample
    return self._sample_beam(fc_feats, att_feats, opt)
  File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 125, in _sample_beam
    batch_size = fc_feats.size(0)
TypeError: 'int' object is not callable
But I didn't find any error in FCModel.py.
Thank you !

**Comment by sssilence** [comment]
@ruotianluo

**Comment by NieGuozhang** [comment]
> python eval.py --model log_fc/model.pth --infos_path infos_fc.pkl --image_folder blah --num_images 10
> DataLoaderRaw loading images from folder: blah0
> listing all images in directory blah
> DataLoaderRaw found 20 images10
> Traceback (most recent call last):
> File "eval.py", line 76, in
> vars(opt))
> File "/home/ps/ws/code/self-critical.pytorch-master/eval_utils.py", line 124, in eval_split
> seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
> File "/home/ps/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/CaptionModel.py", line 32, in forward
> return getattr(self, '_'+mode)(*args, **kwargs)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 156, in _sample
> return self._sample_beam(fc_feats, att_feats, opt)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 125, in _sample_beam
> batch_size = fc_feats.size(0)
> TypeError: 'int' object is not callable
> But I didn't find any error in FCModel.py.
> Thank you !

I guess there is a problem with the parameter passing of your __sample_beam()_ function. The _fc_feats_ you give  is '_int'_ type . You carefully check the previous setting of this parameter.

**Comment by yuchen-ren** [comment]
Can you elaborate? I have the same problem.Thank you! @NieGuozhang

**Comment by Chopper-leey** [comment]
> python eval.py --model log_fc/model.pth --infos_path infos_fc.pkl --image_folder blah --num_images 10
> DataLoaderRaw loading images from folder: blah0
> listing all images in directory blah
> DataLoaderRaw found 20 images10
> Traceback (most recent call last):
> File "eval.py", line 76, in 
> vars(opt))
> File "/home/ps/ws/code/self-critical.pytorch-master/eval_utils.py", line 124, in eval_split
> seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
> File "/home/ps/anaconda3/envs/py27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 541, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/CaptionModel.py", line 32, in forward
> return getattr(self, '_'+mode)(*args, **kwargs)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 156, in _sample
> return self._sample_beam(fc_feats, att_feats, opt)
> File "/home/ps/ws/code/self-critical.pytorch-master/models/FCModel.py", line 125, in _sample_beam
> batch_size = fc_feats.size(0)
> TypeError: 'int' object is not callable
> But I didn't find any error in FCModel.py.
> Thank you !

this is not a big question. The error above is very clearly. you can do it if you debug it carefully.
