### ISSUE TITLE
Running again

### ISSUE THREAD

**Issue by sohamirian** [ruotianluo/self-critical.pytorch#172]
Hi, I could run the code completely last week. But when I want to run it again now it gives me this error:

python eval.py --model model.pth --image_folder blah/inputImageTest/ --num_images 10
loading annotations into memory...
0:00:00.229804
creating index...
index created!
Soheyla! Good Luck!
Traceback (most recent call last):
  File "eval.py", line 71, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/myName/Research/self-critical-pytorch/eval_utils.py", line 92, in language_eval
    mean_entropy = sum([_['entropy'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

I don't know what I can do about it. Help please!

**Comment by ruotianluo** [comment]
Add --language_eval 0.

**Comment by sohamirian** [comment]
Still the same issue :(

python eval.py --model model.pth --image_folder blah/inputImageTest/ --num_images 10  --language_eval 0
loading annotations into memory...
0:00:00.218293
creating index...
index created!
Traceback (most recent call last):
  File "eval.py", line 71, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/myName/Research/self-critical-pytorch/eval_utils.py", line 88, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

**Comment by ruotianluo** [comment]
Doesn't make sense. If language_eval is 0 then language_eval won't be run.

**Comment by sohamirian** [comment]
I don't know what should I do. No other suggestion?

**Comment by sohamirian** [comment]
the pred is not empty:

creating index...
index created!
******preds values******* [{'image_id': '1', 'caption': 'a black dog is in the grass with a frisbee', 'perplexity': 0.8958663940429688, 'entropy': 2.071765184402466}, {'image_id': '2', 'caption': 'a duck standing in a body of water', 'perplexity': 1.0045921802520752, 'entropy': 2.30354380607605}, {'image_id': '3', 'caption': 'a couple of people sitting on a beach with surfboards', 'perplexity': 0.827103853225708, 'entropy': 2.0073392391204834}, {'image_id': '4', 'caption': 'a herd of sheep grazing on a lush green field', 'perplexity': 0.5013392567634583, 'entropy': 1.37556791305542}, {'image_id': '5', 'caption': 'a group of birds standing on top of a lush green field', 'perplexity': 0.6475695371627808, 'entropy': 1.5840824842453003}, {'image_id': '6', 'caption': 'a group of people sitting on a bench bench', 'perplexity': 0.48952656984329224, 'entropy': 1.771714448928833}, {'image_id': '7', 'caption': 'a white and black dog standing in the grass', 'perplexity': 0.9002361297607422, 'entropy': 1.8914852142333984}, {'image_id': '8', 'caption': 'a man wearing a hat and a hat on a bench', 'perplexity': 1.0900344848632812, 'entropy': 3.1836864948272705}]
*******preds_filt values****** []
Traceback (most recent call last):
  File "eval.py", line 71, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/sa39533/Research/self-critical-pytorch/eval_utils.py", line 91, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

**Comment by Ethan-Zhu-code** [comment]
I fixed this issue by deleting the .pth file created in eval_results.

**Comment by sohamirian** [comment]
Thanks. It worked. :)
