### ISSUE TITLE
online evaluation

### ISSUE THREAD

**Issue by 2014gaokao** [ruotianluo/self-critical.pytorch#175]
请问我想在COCO官网上在线评估要对这个代码做哪些步骤呢，谢谢。

**Comment by ruotianluo** [comment]
readme有evaluate on coco test set

**Comment by 2014gaokao** [comment]
恩恩，然后运行的时候出现了下面这个问题，请问应该怎么解决呢，谢谢
vocab size is  9487
DataLoader loading h5 file:  data/cocotest_bu_fc data/cocotest_bu_att data/cocobu_box none
read 40775 image features
assigned 0 images to split train
assigned 0 images to split val
assigned 40775 images to split test
Traceback (most recent call last):
  File "eval.py", line 115, in <module>
    vars(opt))
  File "/data/zcc/self-critical.pytorch/eval_utils.py", line 154, in eval_split
    data = loader.get_batch(split)
  File "/data/zcc/self-critical.pytorch/dataloader.py", line 298, in get_batch
    data = next(self.iters[split])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/data/zcc/self-critical.pytorch/dataloader.py", line 241, in __getitem__
    att_feat = self.att_loader.get(str(self.info['images'][ix]['id']))
  File "/data/zcc/self-critical.pytorch/dataloader.py", line 58, in get
    feat = self.loader(f_input)
  File "/data/zcc/self-critical.pytorch/dataloader.py", line 31, in <lambda>
    self.loader = lambda x: np.load(x)['feat']
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/npyio.py", line 239, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'feat is not a file in the archive'

**Comment by 2014gaokao** [comment]
上面这个问题解决了，我还想问一下readme是在coco test上evaluation，但是COCO官网在线评估不是还需要验证集的吗

**Comment by yuchen-ren** [comment]
@2014gaokao 请问在线评估的那个验证集是怎么解决呢

**Comment by 2014gaokao** [comment]
@yuchen-ren 在dataloader.py里把self.split_ix的不是train的都放到test里

**Comment by yuchen-ren** [comment]
好的感谢，请问可否留个联系方式~~

**Comment by yuchen-ren** [comment]
@2014gaokao  好的感谢，请问可否留个联系方式~~

**Comment by 2014gaokao** [comment]
@yuchen-ren QQ邮箱可以不2225052023@qq.com

**Comment by yuchen-ren** [comment]
@2014gaokao 可以可以，谢谢喽

**Comment by HN123-123** [comment]
@2014gaokao 可以具体说一下验证集获取吗？？没太看懂“在dataloader.py里把self.split_ix的不是train的都放到test里”这个是啥意思？？？
