### ISSUE TITLE
RuntimeError when evaluating Karpathy's test split

### ISSUE THREAD

**Issue by charryglomc** [ruotianluo/self-critical.pytorch#185]
python eval.py --dump_images 0 --num_images 5000 --model model.pth --infos_path infos_fc_rl-best.pkl --language_eval 1
Traceback (most recent call last):
  File "eval.py", line 114, in <module>
    vars(opt))
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/eval_utils.py", line 177, in eval_split
    seq, seq_logprobs = model(fc_feats, att_feats, att_masks, opt=tmp_eval_kwargs, mode='sample')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/models/CaptionModel.py", line 32, in forward
    return getattr(self, '_'+mode)(*args, **kwargs)
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/models/AttModel.py", line 263, in _sample
    return self._sample_beam(fc_feats, att_feats, att_masks, opt)
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/models/AttModel.py", line 219, in _sample_beam
    p_fc_feats, p_att_feats, pp_att_feats, p_att_masks = self._prepare_feature(fc_feats, att_feats, att_masks)
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/models/AttModel.py", line 940, in _prepare_feature
    fc_feats = self.fc_embed(fc_feats)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1370, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
But I didn't find any error in AttModel.py.
Thank you very much!

**Comment by charryglomc** [comment]
@ruotianluo
