### ISSUE TITLE
Error when evaluating on Karpathy's test split

### ISSUE THREAD

**Issue by charryglomc** [ruotianluo/self-critical.pytorch#186]
python eval.py --dump_images 0 --num_images 5000 --model model.pth --infos_path infos_fc_rl-best.pkl --language_eval 1
Traceback (most recent call last):
File "eval.py", line 114, in vars(opt))
File "/content/gdrive/Shared drives/1/eval_utils.py", line 177, in eval_split seq, seq_logprobs = model(fc_feats, att_feats, att_masks, opt=tmp_eval_kwargs, mode='sample')
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in call result = self.forward(*input, **kwargs)
File "/content/gdrive/Shared drives/1/models/CaptionModel.py", line 32, in forward return getattr(self, '_'+mode)(*args, **kwargs)
File "/content/gdrive/Shared drives/1/models/AttModel.py", line 263, in _sample return self._sample_beam(fc_feats, att_feats, att_masks, opt)
File "/content/gdrive/Shared drives/1/models/AttModel.py", line 219, in _sample_beam
p_fc_feats, p_att_feats, pp_att_feats, p_att_masks = self._prepare_feature(fc_feats, att_feats, att_masks)
File "/content/gdrive/Shared drives/1/models/AttModel.py", line 940, in _prepare_feature
fc_feats = self.fc_embed(fc_feats)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/linear.py", line 87, in forward
return F.linear(input, self.weight, self.bias)
File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1370, in linear
ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512] at/pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290
But I didn't find any error in AttModel.py.
Thank you very much!

**Comment by charryglomc** [comment]
@ruotianluo

**Comment by ruotianluo** [comment]
It looks like the use_fc is set to false for some reason. You can manually set it to true in dataloader

**Comment by charryglomc** [comment]
in dataloader.py,use_fc is already set to true. 
so,I try to find other ways.
in misc/utils.py
def if_use_feat(caption_model):
    # Decide if load attention feature according to caption model
    if caption_model in ['show_tell', 'all_img', 'fc', 'newfc']:
        use_att, use_fc = True, True
    elif caption_model == 'language_model':
        use_att, use_fc = True, True
    elif caption_model in ['updown', 'topdown']:
        use_fc, use_att = True, True
    else:
        use_att, use_fc = True, True
    return use_fc, use_att

I fix all use_fc  in this file to true,but in fact,it doesn't work as before

**Comment by charryglomc** [comment]
RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512]
Still this error
Maybe this error is between use_att and use_fc

**Comment by charryglomc** [comment]
RuntimeError: size mismatch, m1: [10 x 0], m2: [2048 x 512]
Still this error
Maybe this error is between use_att and use_fc?

**Comment by ruotianluo** [comment]
Looks weird to me. Can you breakpoint at the _getitem_ in dataloader to see what fc_feats are.

**Comment by ruotianluo** [comment]
Did you download cocotalk_fc?

**Comment by ruotianluo** [comment]
can you tell me what is key and self.ext

**Comment by stephancheng** [comment]
data path is: data/cocotalk
ext is: ".npy"
I am not sure what the key is, but from the code, it is: str(self.info['images'][ix]['id']), where ix is 92800, 
so the key become: 219921

**Comment by ruotianluo** [comment]
Do you mean self.db_path is data/cocotalk? (it should be data/cocotalk_fc)
And, do you have 219921.npy in data/cocotalk_fc?

**Comment by ruotianluo** [comment]
It is supposed to be folder.
