### ISSUE TITLE
Poor results in test

### ISSUE THREAD

**Issue by ly201802004** [ruotianluo/self-critical.pytorch#221]
@ruotianluo 大神您好，我一直有关注您在github和知乎上发表的文章，您在image caption领域的贡献让我受益匪浅。在您的帮助下，我已经成功地将算法移植到自己的数据集，在训练和验证集中都取得了很好的效果。但是在测试raw images(raw image来自数据集划分出的10%测试集）时，先是captioning/utils/eval_utils.py报错Keyerror.详情如下：
Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/../../../captioning/utils/eval_utils.py", line 168, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'labels'
我猜测是因为eval.py错把test当成了valid,没有检索到label信息而报错。当我使用
        if 'labels' not in data:
            data['labels'] = None
        if 'masks' not in data:
            data['masks'] = None
把label部分屏蔽后，能够获得描述结果, 但是描述基本是全错的，比如图像中的目标是飞机，生成的描述却是森林。您知道测试时的问题出在哪里吗？再次感谢！

**Comment by ruotianluo** [comment]
你要不先试一下把test image用同样的预处理成feature files，然后跑一个试试看。dataloaderraw我自己不用，所以不怎么维护，可能是那里有bug。

**Comment by sssilence** [comment]
> @ruotianluo 大神您好，我一直有关注您在github和知乎上发表的文章，您在image caption领域的贡献让我受益匪浅。在您的帮助下，我已经成功地将算法移植到自己的数据集，在训练和验证集中都取得了很好的效果。但是在测试raw images(raw image来自数据集划分出的10%测试集）时，先是captioning/utils/eval_utils.py报错Keyerror.详情如下：
> Traceback (most recent call last):
> File "tools/eval.py", line 117, in
> vars(opt))
> File "/../../../captioning/utils/eval_utils.py", line 168, in eval_split
> tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
> KeyError: 'labels'
> 我猜测是因为eval.py错把test当成了valid,没有检索到label信息而报错。当我使用
> if 'labels' not in data:
> data['labels'] = None
> if 'masks' not in data:
> data['masks'] = None
> 把label部分屏蔽后，能够获得描述结果, 但是描述基本是全错的，比如图像中的目标是飞机，生成的描述却是森林。您知道测试时的问题出在哪里吗？
您好，您在自己的数据集上测试成功了吗？我用bottom-up feature训练的模型，想直接测试自己的数据集，不知道该怎么办。因为Evaluate on raw image那里写的“Note: this doesn't work for models trained with bottomup feature.”

**Comment by ruotianluo** [comment]
你用bottomup feature的话，得先对test image extract bottomup feature
