### ISSUE TITLE
import ERROR and h5py cannot pickle error

### ISSUE THREAD

**Issue by NewUniverseEntrop** [ruotianluo/self-critical.pytorch#234]
你好！！ 

python 3.8 

i had to add **sys.path.append("./")** to allow import captioning to work with comamnd **`python scripts/prepro_ngrams.py`**

when i ran default **python tools/train.py --cfg configs/fc.yml --id fc** on custom dataset   i got following error  **_“h5py cannot be pickled"_** 

DataLoader loading json file:  data/datatalk.json
vocab size is  74
DataLoader loading h5 file:  data/datatalk_fc data/datatalk_att data/cocotalk_box data/datatalk_label.h5
max sequence length in data is 16
read 183 image features
assigned 183 images to split train
assigned 0 images to split val
assigned 0 images to split test
Traceback (most recent call last):
  File "tools/train.py", line 289, in <module>
    train(opt)
  File "tools/train.py", line 38, in train
    loader = DataLoader(opt)
  File ".\captioning\data\dataloader.py", line 324, in __init__
    self.iters[split] = iter(self.loaders[split])
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
    w.start()
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\site-packages\h5py\_hl\base.py", line 372, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled
PS C:\Users\A\Desktop\CSE-576\self-critical.pytorch-master> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\A\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by NewUniverseEntrop** [comment]
ok fixed it by changing num_worker  to 0 because windows limit proc
