### ISSUE TITLE
"IndexError: pop from empty list" when eval

### ISSUE THREAD

**Issue by hungnt14** [ruotianluo/self-critical.pytorch#255]
I got this error while my code was doing eval test cases
I'm training on COCO2017 dataset use with resnet.

Traceback (most recent call last):
  File "tools/train.py", line 296, in <module>
    train(opt)
  File "tools/train.py", line 250, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/content/drive/MyDrive/current_projects/VLSP2021_ImageCaptioning/Hung/self-critical.pytorch/captioning/utils/eval_utils.py", line 207, in eval_split
    predictions.pop()
IndexError: pop from empty list

**Comment by ruotianluo** [comment]
Does it happen when batch_size is 1?

**Comment by qchenjie** [comment]
I also encountered this problem, This is trained on the flickr30 dataset ， and the batch_size is 10 ,

**Comment by hungnt14** [comment]
I fixed it by putting some `if` statements to prevent this error happen. And the training process has worked. I don't know whether this change can affect the result, but it works xD
