### ISSUE TITLE
java' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by zghorbani** [ruotianluo/self-critical.pytorch#263]
when  running the Train using self critical,
I get the following error:

```
java' is not recognized as an internal or external command,
operable program or batch file.
'java' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "tools/train.py", line 296, in <module>
    train(opt)
  File "tools/train.py", line 250, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "f:\self-critical.pytorch\captioning\utils\eval_utils.py", line 222, in eval_split
    lang_stats = language_eval(dataset, predictions, n_predictions, eval_kwargs, split)
  File "f:\self-critical.pytorch\captioning\utils\eval_utils.py", line 87, in language_eval
    cocoEval.evaluate()
  File "coco-caption\pycocoevalcap\eval.py", line 51, in evaluate
    (WMD(),   "WMD"),
  File "coco-caption\pycocoevalcap\wmd\wmd.py", line 17, in __init__
    self.model = gensim.models.KeyedVectors.load_word2vec_format(os.path.join(os.path.abspath(os.path.dirname(__file__)), 'data', 'GoogleNews-vectors-negative300.bin'), binary=True)
  File "C:\Users\Anaconda3\envs\SATIC\lib\site-packages\gensim\models\keyedvectors.py", line 1631, in load_word2vec_format
```

how can fix this?

**Comment by ruotianluo** [comment]
Run the last step of https://github.com/ruotianluo/coco-caption/tree/ea20010419a955fed9882f9dcc53f2dc1ac65092#setup. Or just comment out that line in eval.py.

**Comment by zghorbani** [comment]
Thank you. Its ok but how long does it take to run? The second running of "UpDown+new_self_critical" model started  a week ago.

**Comment by zghorbani** [comment]
Thanks. It's ok but how long does it take to run? The second running of "UpDown+new_self_critical" model started a week ago.
