### ISSUE TITLE
transformer_nsc

### ISSUE THREAD

**Issue by bai-24** [ruotianluo/self-critical.pytorch#277]
你好，我在运行transformer_nsc.yml时，碰到以下问题，请问怎么解决？
Hugginface transformers not installed; please visit https://github.com/huggingface/transformers
meshed-memory-transformer not installed; please run `pip install git+https://github.com/ruotianluo/meshed-memory-transformer.git`
Warning: coco-caption not available

**Comment by ruotianluo** [comment]
无视就可以了

**Comment by bai-24** [comment]
好的， 感谢，请问要训练transformer+nsc的话，直接运行transformer_nsc.yml就可以了吗？还是有什么先后顺序？

**Comment by ruotianluo** [comment]
应该还是要先用transformer.yml，然后再到nsc

**Comment by bai-24** [comment]
你好，请问用transformer.yml训练完后，不小心关了界面，Bleu、Meteor、Rouge等评价指标在哪里可以看见呢

**Comment by ruotianluo** [comment]
Tensorboard

**Comment by bai-24** [comment]
请问在生成图像描述时，出现以下错误，有什么解决办法吗？
Traceback (most recent call last):
  File "tools/eval.py", line 77, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "g:\self-critical.pytorch\captioning\utils\eval_utils.py", line 80, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

**Comment by ruotianluo** [comment]
command是什么

**Comment by bai-24** [comment]
输入为：python tools/eval.py --model log_fc_nsc/model-best.pth --infos_path log_fc_nsc/infos_fc_nsc-best.pkl --image_folder blah --num_images 10

**Comment by ruotianluo** [comment]
大多数pretrained 模型不支持任意图片的captioning，如果你想试任意图片，可以用readme里面的colab

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/self-critical.pytorch#evaluate-on-karpathys-test-split

**Comment by bai-24** [comment]
请问transformer训练时，可以使用Resnet101 feature吗？

**Comment by ruotianluo** [comment]
没试过，应该是可以的。因为resnet101比较长，训练比较慢我后来都不用了Ruotian LuoOn Jan 16, 2023, at 9:08 AM, bai-24 ***@***.***> wrote:﻿
请问transformer训练时，可以使用Resnet101 feature吗？
