### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by AdamTTong** [ruotianluo/self-critical.pytorch#38]
你好，我想请问一下我训练好模型之后要如何在测试集上面测试然后上传到网上得到结果呢？谢谢

**Comment by AdamTTong** [comment]
我提交到网上的时候报错了，按照他们给的那个格式提交的
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/tmp/codalab/tmp7txC6i/run/program/cocoEvalCapCoda.py", line 68, in 
    cocoEval.evaluate()
  File "/tmp/codalab/tmp7txC6i/run/program/pycocoevalcap/eval.py", line 24, in evaluate
    res[imgId] = self.cocoRes.imgToAnns[imgId]
KeyError: 536
你能看看是什么原因吗？

**Comment by AdamTTong** [comment]
找到原因是因为有重复的，我再看看程序
