### ISSUE TITLE
你好,训练的时候遇到了keyerror错误?

### ISSUE THREAD

**Issue by enjoy4** [ruotianluo/self-critical.pytorch#68]
Traceback (most recent call last):
  File "/media/enjoy/32F872CFF87290B9/CODE/self-critical.pytorch-master/train.py", line 224, in <module>
    train(opt)
  File "/media/enjoy/32F872CFF87290B9/CODE/self-critical.pytorch-master/train.py", line 113, in train
    data = loader.get_batch('train')
  File "/media/enjoy/32F872CFF87290B9/CODE/self-critical.pytorch-master/dataloader.py", line 136, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "/media/enjoy/32F872CFF87290B9/CODE/self-critical.pytorch-master/dataloader.py", line 283, in get
    tmp = self.split_loader.next()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 286, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 307, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 57, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/media/enjoy/32F872CFF87290B9/CODE/self-critical.pytorch-master/dataloader.py", line 204, in __getitem__\n    h,w = self.info[\'images\'][ix][\'height\'], self.info[\'images\'][ix][\'width\']\nKeyError: \'height\'\n'
Terminating BlobFetcher

**Comment by ruotianluo** [comment]
Don't use use_box

**Comment by NonaryR** [comment]
@ruotianluo hello! is this affected somehow on training with bottom-up features?

**Comment by ruotianluo** [comment]
@NonaryR I acutally didn't find it to be useful.
