### ISSUE TITLE
evaluation error using Karpathy's test split

### ISSUE THREAD

**Issue by DurraniBit** [ruotianluo/self-critical.pytorch#86]
Hi Ruotian,,
I tried to run the following script:
python eval.py --dump_images 0 --num_images 500 --model log_fc/model-best.pth --infos_path log_fc/infos_fc-best.pkl --language_eval 1
But at the end I got the below error. 

evaluating validation preformance... 499/500 (0.000000)
loading annotations into memory...
0:00:00.811912
creating index...
index created!
using 500/500 predictions
Loading and preparing results...     
DONE (t=0.03s)
creating index...
index created!
tokenization...
Traceback (most recent call last):
  File "eval.py", line 143, in <module>
    loss, split_predictions, lang_stats = eval_utils.eval_split(model, crit, loader, vars(opt))
  File "/home/Durrani/icp/self-critical.pytorch/eval_utils.py", line 158, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/home/Durrani/icp/self-critical.pytorch/eval_utils.py", line 52, in language_eval
    cocoEval.evaluate()
  File "coco-caption/pycocoevalcap/eval.py", line 32, in evaluate
    gts  = tokenizer.tokenize(gts)
  File "coco-caption/pycocoevalcap/tokenizer/ptbtokenizer.py", line 52, in tokenize
    stdout=subprocess.PIPE)
  File "/home/Durrani/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/Durrani/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
-------------------------------------------------
Anybody who implement this code your reply will be appreciated.  thanks

**Comment by jamiechoi1995** [comment]
@DurraniBit how did you solve it?

**Comment by DurraniBit** [comment]
As for the coco-caption java is necessary when I Install java on the server then the error is solved.
